moved glsl in it's own directory and set bgDaemon as a systemctl daemon 	modified:   custom/keybinds.conf 	new file:   custom/scripts/background/README 	new file:   custom/scripts/background/bgDaemon 	new file:   custom/scripts/background/bgDaemon.service 	modified:   custom/scripts/backgroundGL 	new file:   glpaper.pid 	modified:   hyprland/colors.conf 	modified:   hyprlock.conf 	renamed:    shaders/blob.glsl -> shaders/glsl/blob.glsl 	renamed:    shaders/galaxy.glsl -> shaders/glsl/galaxy.glsl 	renamed:    shaders/glitch.glsl -> shaders/glsl/glitch.glsl 	renamed:    shaders/hg.glsl -> shaders/glsl/hg.glsl 	renamed:    shaders/lights.glsl -> shaders/glsl/lights.glsl 	renamed:    shaders/lights2.glsl -> shaders/glsl/lights2.glsl 	renamed:    shaders/lights3.glsl -> shaders/glsl/lights3.glsl 	renamed:    shaders/lights4.glsl -> shaders/glsl/lights4.glsl 	renamed:    shaders/nid.glsl -> shaders/glsl/nid.glsl 	renamed:    shaders/nid2.glsl -> shaders/glsl/nid2.glsl 	renamed:    shaders/psyche.glsl -> shaders/glsl/psyche.glsl 	renamed:    shaders/psyche2.glsl -> shaders/glsl/psyche2.glsl 	renamed:    shaders/purplerain.glsl -> shaders/glsl/purplerain.glsl 	renamed:    shaders/see.glsl -> shaders/glsl/see.glsl 	renamed:    shaders/shad2.glsl -> shaders/glsl/shad2.glsl 	renamed:    shaders/shad3.glsl -> shaders/glsl/shad3.glsl 	renamed:    shaders/shad4.glsl -> shaders/glsl/shad4.glsl 	renamed:    shaders/shad5.glsl -> shaders/glsl/shad5.glsl 	renamed:    shaders/shad6.glsl -> shaders/glsl/shad6.glsl 	renamed:    shaders/shader.glsl -> shaders/glsl/shader.glsl 	renamed:    shaders/sky.glsl -> shaders/glsl/sky.glsl 	renamed:    shaders/sky2.glsl -> shaders/glsl/sky2.glsl 	renamed:    shaders/stars.glsl -> shaders/glsl/stars.glsl 	renamed:    shaders/stars2.glsl -> shaders/glsl/stars2.glsl 	renamed:    shaders/stars3.glsl -> shaders/glsl/stars3.glsl 	renamed:    shaders/terrain.glsl -> shaders/glsl/terrain.glsl 	renamed:    shaders/tunnel1.glsl -> shaders/glsl/tunnel1.glsl 	renamed:    shaders/tunnel2.glsl -> shaders/glsl/tunnel2.glsl 	renamed:    shaders/vec.glsl -> shaders/glsl/vec.glsl 	renamed:    shaders/vec2.glsl -> shaders/glsl/vec2.glsl 	renamed:    shaders/vibe.glsl -> shaders/glsl/vibe.glsl 	renamed:    shaders/vibe2.glsl -> shaders/glsl/vibe2.glsl

diff --git a/custom/scripts/backgroundGL b/custom/scripts/backgroundGL
--- a/custom/scripts/backgroundGL
+++ b/custom/scripts/backgroundGL
@@ -1,41 +1,43 @@
-#!/usr/bin/env bash
-OS=$(uname -s)
+#!/bin/bash
 
-VIDEO_DEVICE_ID=$(~/.config/hypr/custom/scripts/videoid)
-GLSL_FILES=($(find ~/.config/hypr/shaders/ -name "*.glsl"))
-REFRESH_TIME=30
+# Chemin vers le script bgDaemon
+BGDAEMON_PATH=~/.local/bin/glpaper/bgDaemon
 
-if pgrep -f "glpaper $VIDEO_DEVICE_ID" > /dev/null
-then
-    pkill -f "glpaper $VIDEO_DEVICE_ID"
-    notify-send --icon=dialog-warning "$USER" "GLSL KILLED ${TIMECODE} " > /dev/null 2>&1
-fi
+# Fonction pour envoyer les commandes à bgDaemon
+send_command_to_bgdaemon() {
+  "$BGDAEMON_PATH" "$@"
+}
 
-NEXT_REFRESH=$(( $(date +%s) + $REFRESH_TIME ))
-TIMECODE=$(( $(date +%s) / $REFRESH_TIME ))
-notify_file=$(basename "${GLSL_FILES[${RANDOM:0:1}%${#GLSL_FILES[@]}]}" .glsl)
-notify_file="${notify_file##*/}"
-notify-send --icon=dialog-warning "$USER" "LETS GLSL $(date -u -d @${TIMECODE} '+%H:%M:%S') ${notify_file}" > /dev/null 2>&1
-
-while [ $(date +%s) -lt $NEXT_REFRESH ]
-do
-    glpaper $VIDEO_DEVICE_ID "${GLSL_FILES[${RANDOM:0:1}%${#GLSL_FILES[@]}]}" &
-    sleep $REFRESH_TIME
-done
-
-
+# Vérifier les conditions et agir en conséquent
+if ! pgrep glpaper > /dev/null; then
+  # Aucun processus glpaper n'est actuellement en cours d'exécution,
+  # donc on démarre un nouveau processus.
+  if [[ -z "$1" ]]; then
+    snd-notify 'Glpaper' 'Aucune sequence n''est en cours de lecture'
+  else
+    send_command_to_bgdaemon start
+  fi
+elif [[ -n "$1" ]]; then
+  case "$1" in
+    next)
+      # Navigation vers le GLSL suivant
+      send_command_to_bgdaemon next
+      ;;
+    prev)
+      # Navigation vers le GLSL précédent
+      send_command_to_bgdaemon prev
+      ;;
+    *)
+      echo "Option invalide: $1"
+      exit 1
+      ;;
+  esac
 else
-    notify-send --icon=dialog-warning "$USER" "Erreur : la valeur stockée dans ~/.config/hypr/custom/scripts/videoid n'est pas un entier" > /dev/null 2>&1
- 
-    if [[ $VIDEO_DEVICE_ID =~ ^[0-9]+$ ]]
-    then
-        echo $VIDEO_DEVICE_ID > ~/.config/hypr/custom/scripts/videoid
-        glpaper $VIDEO_DEVICE_ID ~/.config/hypr/shaders/hg.glsl
-    else
-        notify-send --icon=dialog-warning "$USER" "Impossible de récupérer l'ID du VIDEO DEVICE" > /dev/null 2>&1
-    fi
+  # Un processus glpaper est en cours d'exécution et aucune navigation n'est demandée,
+  # on arrête donc le processus et on termine backgroundGL.
+  send_command_to_bgdaemon stop
+  pkill -f backgroundGL
 fi
 
-
-
+exit 0
 
